
# Pandemic/X86\xpy.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf6\x82\x12d|\xcc\xa2\x0e\x05{\xb6#\x8a\x11\xa4\x1e'
    
_lr_action_items = {'Gw':([4,7,13,30,31,32,36,38,50,51,58,],[8,8,23,8,8,42,23,23,8,8,23,]),'XMM':([4,7,30,31,50,51,],[12,12,12,12,12,12,]),'CNT':([4,7,30,31,50,51,],[10,10,10,10,10,10,]),'Gd':([4,7,13,30,31,33,36,38,50,51,58,],[17,17,25,17,17,45,25,25,17,17,25,]),'Seg':([4,7,29,30,31,50,51,],[15,15,39,15,15,15,15,]),'MMX':([4,7,30,31,50,51,],[11,11,11,11,11,11,]),'TIMES':([25,45,],[34,54,]),'COLON':([15,19,39,],[27,28,49,]),'NUM':([4,7,13,28,30,31,32,33,34,36,38,50,51,52,53,54,55,58,66,],[19,19,24,37,19,19,43,44,46,24,24,19,19,61,62,63,64,24,68,]),'LSQBR':([4,7,27,29,30,31,49,50,51,],[13,13,36,38,13,13,58,13,13,]),'DBG':([4,7,30,31,50,51,],[14,14,14,14,14,14,]),'PLUS':([23,25,42,45,46,63,],[32,33,52,53,55,66,]),'FPU':([4,7,30,31,50,51,],[9,9,9,9,9,9,]),'Mnem':([0,2,5,6,],[4,7,-30,-31,]),'COMMA':([8,9,10,11,12,14,15,16,17,18,19,21,22,35,37,40,41,56,57,67,],[-2,-7,-5,-8,-9,-6,-4,-27,-3,-1,-29,30,31,-26,-28,50,51,-25,-23,-24,]),'Gb':([4,7,30,31,50,51,],[18,18,18,18,18,18,]),'RSQBR':([23,24,25,26,42,43,44,45,46,47,48,61,62,63,64,65,68,],[-22,-18,-17,35,-20,-21,-16,-15,-14,56,57,-19,-11,-12,-13,67,-10,]),'PFX':([0,2,5,6,],[5,6,-30,-31,]),'SIZE':([4,7,30,31,50,51,],[20,20,20,20,20,20,]),'PTR':([20,],[29,]),'$end':([1,3,4,7,8,9,10,11,12,14,15,16,17,18,19,21,22,35,37,40,41,56,57,59,60,67,],[0,-40,-39,-35,-2,-7,-5,-8,-9,-6,-4,-27,-3,-1,-29,-38,-34,-26,-28,-37,-33,-25,-23,-36,-32,-24,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instr':([0,],[1,]),'pfxlist':([0,],[2,]),'pseudo':([0,],[3,]),'memexpr':([4,7,30,31,50,51,],[16,16,16,16,16,16,]),'meminner':([13,36,38,58,],[26,47,48,65,]),'op':([4,7,30,31,50,51,],[21,22,40,41,59,60,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> instr","S'",1,None,None,None),
  ('op -> Gb','op',1,'p_op_gb','Pandemic\\X86\\X86Yacc.py',60),
  ('op -> Gw','op',1,'p_op_gw','Pandemic\\X86\\X86Yacc.py',64),
  ('op -> Gd','op',1,'p_op_gd','Pandemic\\X86\\X86Yacc.py',68),
  ('op -> Seg','op',1,'p_op_seg','Pandemic\\X86\\X86Yacc.py',72),
  ('op -> CNT','op',1,'p_op_cnt','Pandemic\\X86\\X86Yacc.py',76),
  ('op -> DBG','op',1,'p_op_dbg','Pandemic\\X86\\X86Yacc.py',80),
  ('op -> FPU','op',1,'p_op_fpu','Pandemic\\X86\\X86Yacc.py',84),
  ('op -> MMX','op',1,'p_op_mmx','Pandemic\\X86\\X86Yacc.py',88),
  ('op -> XMM','op',1,'p_op_xmm','Pandemic\\X86\\X86Yacc.py',92),
  ('meminner -> Gd PLUS Gd TIMES NUM PLUS NUM','meminner',7,'p_meminner_Gd_plus_Gd_times_num_plus_num','Pandemic\\X86\\X86Yacc.py',96),
  ('meminner -> Gd PLUS Gd PLUS NUM','meminner',5,'p_meminner_Gd_plus_Gd_plus_num','Pandemic\\X86\\X86Yacc.py',100),
  ('meminner -> Gd PLUS Gd TIMES NUM','meminner',5,'p_meminner_Gd_plus_Gd_times_num','Pandemic\\X86\\X86Yacc.py',104),
  ('meminner -> Gd TIMES NUM PLUS NUM','meminner',5,'p_meminner_Gd_times_num_plus_num','Pandemic\\X86\\X86Yacc.py',108),
  ('meminner -> Gd TIMES NUM','meminner',3,'p_meminner_Gd_times_num','Pandemic\\X86\\X86Yacc.py',112),
  ('meminner -> Gd PLUS Gd','meminner',3,'p_meminner_Gd_plus_Gd','Pandemic\\X86\\X86Yacc.py',116),
  ('meminner -> Gd PLUS NUM','meminner',3,'p_meminner_Gd_plus_num','Pandemic\\X86\\X86Yacc.py',120),
  ('meminner -> Gd','meminner',1,'p_meminner_Gd','Pandemic\\X86\\X86Yacc.py',124),
  ('meminner -> NUM','meminner',1,'p_meminner_num','Pandemic\\X86\\X86Yacc.py',128),
  ('meminner -> Gw PLUS Gw PLUS NUM','meminner',5,'p_meminner_Gw_plus_Gw_plus_num','Pandemic\\X86\\X86Yacc.py',132),
  ('meminner -> Gw PLUS Gw','meminner',3,'p_meminner_Gw_plus_Gw','Pandemic\\X86\\X86Yacc.py',136),
  ('meminner -> Gw PLUS NUM','meminner',3,'p_meminner_Gw_plus_num','Pandemic\\X86\\X86Yacc.py',140),
  ('meminner -> Gw','meminner',1,'p_meminner_Gw','Pandemic\\X86\\X86Yacc.py',144),
  ('memexpr -> SIZE PTR LSQBR meminner RSQBR','memexpr',5,'p_memexpr_size_meminner','Pandemic\\X86\\X86Yacc.py',148),
  ('memexpr -> SIZE PTR Seg COLON LSQBR meminner RSQBR','memexpr',7,'p_memexpr_size_seg_meminner','Pandemic\\X86\\X86Yacc.py',154),
  ('memexpr -> Seg COLON LSQBR meminner RSQBR','memexpr',5,'p_memexpr_seg_meminner','Pandemic\\X86\\X86Yacc.py',161),
  ('memexpr -> LSQBR meminner RSQBR','memexpr',3,'p_memexpr_meminner','Pandemic\\X86\\X86Yacc.py',167),
  ('op -> memexpr','op',1,'p_op_memexpr','Pandemic\\X86\\X86Yacc.py',172),
  ('op -> NUM COLON NUM','op',3,'p_op_ap32','Pandemic\\X86\\X86Yacc.py',176),
  ('op -> NUM','op',1,'p_op_imm','Pandemic\\X86\\X86Yacc.py',180),
  ('pfxlist -> PFX','pfxlist',1,'p_pfxlist_pfx','Pandemic\\X86\\X86Yacc.py',184),
  ('pfxlist -> pfxlist PFX','pfxlist',2,'p_pfxlist_pfxlist_pfx','Pandemic\\X86\\X86Yacc.py',188),
  ('pseudo -> pfxlist Mnem op COMMA op COMMA op','pseudo',7,'p_pfxlist_pseudo3','Pandemic\\X86\\X86Yacc.py',193),
  ('pseudo -> pfxlist Mnem op COMMA op','pseudo',5,'p_pfxlist_pseudo2','Pandemic\\X86\\X86Yacc.py',197),
  ('pseudo -> pfxlist Mnem op','pseudo',3,'p_pfxlist_pseudo1','Pandemic\\X86\\X86Yacc.py',201),
  ('pseudo -> pfxlist Mnem','pseudo',2,'p_pfxlist_pseudo','Pandemic\\X86\\X86Yacc.py',205),
  ('pseudo -> Mnem op COMMA op COMMA op','pseudo',6,'p_pseudo3','Pandemic\\X86\\X86Yacc.py',209),
  ('pseudo -> Mnem op COMMA op','pseudo',4,'p_pseudo2','Pandemic\\X86\\X86Yacc.py',213),
  ('pseudo -> Mnem op','pseudo',2,'p_pseudo1','Pandemic\\X86\\X86Yacc.py',217),
  ('pseudo -> Mnem','pseudo',1,'p_pseudo','Pandemic\\X86\\X86Yacc.py',221),
  ('instr -> pseudo','instr',1,'p_instr_pseudo','Pandemic\\X86\\X86Yacc.py',225),
]
